admin_admin:
    resource: "@AdminAdminBundle/Controller/"
    type:     annotation
    prefix:   /

iia_web_service:
    resource: "@IIAwebServiceBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

