<?php

namespace IIA\webServiceBundle\Entity;

/**
 * QcmUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QcmUserRepository extends \Doctrine\ORM\EntityRepository
{
}
