<?php

namespace IIA\webServiceBundle\Repository;

/**
 * QcmUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QcmUserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * Find all fds with Chemical product Identifier parameter.
    *
    * @return PersistentCollection
    */
   public function myFindUserQcm($idQcm, $idUser)
   {
       $qb = $this->createQueryBuilder('uq');

       $qb->where('uq.qcm =' . $idQcm);
       $qb->andWhere('uq.user =' . $idUser);

       return $qb->getQuery()->setMaxResults(1)->getSingleResult();
   }
}
